/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author admin
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/LOGO_FInal-removebg-preview.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        IDENTIFICACION_USUARIO = new javax.swing.JLabel();
        jTextField_EQUIPO = new javax.swing.JTextField();
        IDENTIFICACION_USUARIO1 = new javax.swing.JLabel();
        jTextField_EQUIPO1 = new javax.swing.JTextField();
        IDENTIFICACION_USUARIO2 = new javax.swing.JLabel();
        IDENTIFICACION_USUARIO3 = new javax.swing.JLabel();
        jTextField_EQUIPO2 = new javax.swing.JTextField();
        jTextField_EQUIPO3 = new javax.swing.JTextField();
        IDENTIFICACION_USUARIO5 = new javax.swing.JLabel();
        jTextField_EQUIPO4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        IDENTIFICACION_USUARIO6 = new javax.swing.JLabel();
        jTextField_EQUIPO5 = new javax.swing.JTextField();
        IDENTIFICACION_USUARIO8 = new javax.swing.JLabel();
        IDENTIFICACION_USUARIO7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        IDENTIFICACION_USUARIO4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(900, 600));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LOGO_FInal-removebg-preview.png"))); // NOI18N
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pngtree-orange-bustling-city-silhouette-background-image_590176.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 170, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Reporte de mantenimiento");

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(187, 187, 187)
                .addComponent(jButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        IDENTIFICACION_USUARIO.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO.setText("S/N");
        Background.add(IDENTIFICACION_USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 20));

        jTextField_EQUIPO.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPOActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 190, -1));

        IDENTIFICACION_USUARIO1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO1.setText("Fecha (dd/mm/aa)");
        Background.add(IDENTIFICACION_USUARIO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 20));

        jTextField_EQUIPO1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPO1ActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, -1));

        IDENTIFICACION_USUARIO2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO2.setText("Identificacion del cliente");
        Background.add(IDENTIFICACION_USUARIO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 20));

        IDENTIFICACION_USUARIO3.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        IDENTIFICACION_USUARIO3.setText("Datos del equipo:");
        Background.add(IDENTIFICACION_USUARIO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        jTextField_EQUIPO2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPO2ActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, -1));

        jTextField_EQUIPO3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPO3ActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, -1));

        IDENTIFICACION_USUARIO5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO5.setText("Marca");
        Background.add(IDENTIFICACION_USUARIO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 20));

        jTextField_EQUIPO4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPO4ActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        IDENTIFICACION_USUARIO6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO6.setText("Modelo");
        Background.add(IDENTIFICACION_USUARIO6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 20));

        jTextField_EQUIPO5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextField_EQUIPO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EQUIPO5ActionPerformed(evt);
            }
        });
        Background.add(jTextField_EQUIPO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 190, -1));

        IDENTIFICACION_USUARIO8.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        IDENTIFICACION_USUARIO8.setText("Datos del equipo:");
        Background.add(IDENTIFICACION_USUARIO8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 20));

        IDENTIFICACION_USUARIO7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        IDENTIFICACION_USUARIO7.setText("Identificacion del equipo");
        Background.add(IDENTIFICACION_USUARIO7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 20));

        jCheckBox1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCheckBox1.setText("Preventivo");
        Background.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCheckBox2.setText("Evaluación");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        Background.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jCheckBox3.setText("Correctivo");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        Background.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Desarrollo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Mediciones");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Herramientas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel6)))
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Background.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 670, 330));

        IDENTIFICACION_USUARIO4.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        IDENTIFICACION_USUARIO4.setText("Tipo de mantenimiento:");
        Background.add(IDENTIFICACION_USUARIO4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 140, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Background.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 150, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton1.setText("Más opciones");
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_EQUIPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPOActionPerformed

    private void jTextField_EQUIPO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPO1ActionPerformed

    private void jTextField_EQUIPO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPO2ActionPerformed

    private void jTextField_EQUIPO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPO3ActionPerformed

    private void jTextField_EQUIPO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPO4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPO4ActionPerformed

    private void jTextField_EQUIPO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EQUIPO5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EQUIPO5ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel IDENTIFICACION_USUARIO;
    private javax.swing.JLabel IDENTIFICACION_USUARIO1;
    private javax.swing.JLabel IDENTIFICACION_USUARIO2;
    private javax.swing.JLabel IDENTIFICACION_USUARIO3;
    private javax.swing.JLabel IDENTIFICACION_USUARIO4;
    private javax.swing.JLabel IDENTIFICACION_USUARIO5;
    private javax.swing.JLabel IDENTIFICACION_USUARIO6;
    private javax.swing.JLabel IDENTIFICACION_USUARIO7;
    private javax.swing.JLabel IDENTIFICACION_USUARIO8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField_EQUIPO;
    private javax.swing.JTextField jTextField_EQUIPO1;
    private javax.swing.JTextField jTextField_EQUIPO2;
    private javax.swing.JTextField jTextField_EQUIPO3;
    private javax.swing.JTextField jTextField_EQUIPO4;
    private javax.swing.JTextField jTextField_EQUIPO5;
    // End of variables declaration//GEN-END:variables
}
